dataset:
  target: dataloader.TMRef.TMRefCascadeDataset
  params:
    # Path to the file list.
    dataroot: ../../../experiments/03_scgm_subset_reproduction/outputs/scgm_official_local_bridge/val
    datalist: tilelist_18_16_3L.csv
    scale: 2
    size: 256
    split: "test"
    data_len: -1
    use_cascade: true
    use_txt: true
    txt_level: false
    txt_feature: false
    cascade_path: ../../../experiments/03_scgm_subset_reproduction/outputs/scgm_official_local_bridge/cascade_seed_samples
    #style_path: none

data_loader:
  batch_size: 20
  shuffle: false
  num_workers: 4
  drop_last: false

batch_transform:
  target: dataloader.batch_transform.IdentityBatchTransform
